name: php-cs-fixer

on:
    push:
        paths:
            - '**.php'
            - '.github/workflows/php-cs-fixer.yml'
            - 'composer.lock'
    pull_request:
        paths:
            - '**.php'
            - '.github/workflows/php-cs-fixer.yml'
            - 'composer.lock'

jobs:
    php-cs-fixer:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2

            -   name: Setup php
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.0
                    coverage: none

            -   name: Cache composer dependencies
                uses: actions/cache@v2
                with:
                    path: vendor
                    key: composer-${{ hashFiles('composer.lock') }}

            -   name: Install dependencies
                run: composer install --prefer-dist --no-interaction

            -   name: Run php-cs-fixer
                run: vendor/bin/php-cs-fixer fix --dry-run
