name: php-cs-fixer

on:
    push:
        branches:
            - master

jobs:
    php-cs-fixer:
        uses: devmoath/reusable-workflows/.github/workflows/php-cs-fixer.yml@master
        with:
            php-version: 8.1
            php-extensions: dom, libxml, mbstring
