name: phpstan

on:
    push:
    pull_request:

jobs:
    phpstan:
        uses: devmoath/reusable-workflows/.github/workflows/phpstan.yml@master
        with:
            php-version: 8.1
            php-extensions: dom, libxml, mbstring
