name: Tests

on:
    push:
    pull_request:

jobs:
    tests:
        uses: devmoath/reusable-workflows/.github/workflows/php-tests.yml@master
        with:
            php-versions: "['8.0', 8.1, 8.2]"
            php-extensions: dom, libxml, mbstring
