name: tests

on:
    push:
        paths:
            - '**.php'
            - '.github/workflows/tests.yml'
            - 'composer.lock'
    pull_request:
        paths:
            - '**.php'
            - '.github/workflows/tests.yml'
            - 'composer.lock'

jobs:
    phpunit:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: [ 8.0, 8.1 ]

        name: php@${{ matrix.php }}

        steps:
            -   uses: actions/checkout@v2

            -   name: Setup php
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: dom, libxml, mbstring
                    coverage: none

            -   name: Cache composer dependencies
                uses: actions/cache@v2
                with:
                    path: vendor
                    key: composer-${{ hashFiles('composer.lock') }}

            -   name: Install dependencies
                run: composer install --prefer-dist --no-interaction

            -   name: Run tests
                run: composer test
